"""
tests/test_sim.py

Unit tests for the building energy simulation project.

These tests validate that:
- Weather data generated by synthetic_weather() follows the expected schema.
- The 1R1C simulation produces physically consistent outputs (invariants).
- The simulation is deterministic (same inputs -> same outputs).
"""

import pandas as pd
# import pytest

from core.sim import BuildingParams, simulate_RC
from core.validation import synthetic_weather, validate_weather_schema


def test_weather_schema():
    """
    Ensure that synthetic_weather() produces a DataFrame with
    the correct schema (DatetimeIndex, required columns, sorted).
    """
    wx = synthetic_weather(24)
    validate_weather_schema(wx)


def test_sim_invariants_and_heating():
    """
    Check simulation invariants:
    - Electrical energy consumption is always non-negative.
    - Timeline is strictly increasing in time.
    - HVAC heating occurs at least once when initial temp < heating setpoint.
    """
    wx = synthetic_weather(24)
    params = BuildingParams(C=30e6, R=0.005, A_solar=10.0, g_solar=0.5, ACH=0.5, V=250)
    sim = simulate_RC(wx, params, T0=18, setpoint_heat=20, setpoint_cool=26)
    assert (sim["E_elec_kWh"] >= 0).all()
    assert sim.index.is_monotonic_increasing
    assert sim["Q_hvac_W"].gt(0).any()


def test_determinism():
    """
    Verify that the simulation is deterministic:
    running it twice with the same inputs yields identical outputs.
    """
    wx = synthetic_weather(24)
    params = BuildingParams(C=30e6, R=0.005, A_solar=10.0, g_solar=0.5, ACH=0.5, V=250)
    sim1 = simulate_RC(wx, params, T0=21)
    sim2 = simulate_RC(wx, params, T0=21)
    pd.testing.assert_frame_equal(sim1, sim2, check_dtype=False)
